source "https://rubygems.org"

gem 'spidey', git: 'git@github.com:joeyAghion/spidey'
gem 'spidey-mongo', git: 'git@github.com:joeyAghion/spidey-mongo.git'
gem 'activesupport'

gem 'pry'
gem 'pry-debugger'
