#! /usr/bin/env ruby

require 'bundler'
require 'logger'

path = File.expand_path(File.dirname(__FILE__))
spider = ARGV.shift
debug  = ARGV.shift == 'debug'

ENV['BUNDLE_GEMFILE'] = path + '/../Gemfile'

Bundler.require
Dotenv.load(path + '/../.env')

$LOAD_PATH.unshift path + '/../lib'
require 'recon'

Spidey.logger = Logger.new("#{path}/../log/spidey.log") unless debug

require path + '/../spiders/' + spider
spider_class = spider.camelize.constantize

spider_class.crawl
